### ISSUE TITLE
non-english streamers

### ISSUE THREAD

**Issue by mishelashala** [bnb/awesome-developer-streams#140]
Could you add a section for non-english streamers?

**Comment by mblayman** [comment]
Hi, @mishelashala, good question. Many of the listings include "Languages Spoken During Stream" which acts as the guide for non-English streamers.

The list purposefully avoids categorization of any kind because there are many different ways people read this list. It's hard to prioritize categorization. Should we group by programming language? Should we group by spoken language? Should we group by subject matter? There's no right answer here, so, to be as accessible to all, the list is flat in structure.

I hope that helps. I know that each stream does not list the spoken language so that's a possible area for improvement in the future.
